//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinefilo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cinefilo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Button_Skip {
            get {
                return ResourceManager.GetString("Button_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string BuyTicket_CardCVV {
            get {
                return ResourceManager.GetString("BuyTicket_CardCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card expiration.
        /// </summary>
        public static string BuyTicket_CardExpiration {
            get {
                return ResourceManager.GetString("BuyTicket_CardExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder.
        /// </summary>
        public static string BuyTicket_CardHolder {
            get {
                return ResourceManager.GetString("BuyTicket_CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string BuyTicket_CardNumber {
            get {
                return ResourceManager.GetString("BuyTicket_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        public static string BuyTicket_Month_Format {
            get {
                return ResourceManager.GetString("BuyTicket_Month_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYYY.
        /// </summary>
        public static string BuyTicket_Year_Format {
            get {
                return ResourceManager.GetString("BuyTicket_Year_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QR images located in the movie&apos;s strategic points will allow you to obtain discounts, try it !!.
        /// </summary>
        public static string Collect_Message_Bottom {
            get {
                return ResourceManager.GetString("Collect_Message_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get discount by QR code.
        /// </summary>
        public static string Collect_Title {
            get {
                return ResourceManager.GetString("Collect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the information required to continue.
        /// </summary>
        public static string Default_Fill_Data {
            get {
                return ResourceManager.GetString("Default_Fill_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string DetailMoview_BuyTicket {
            get {
                return ResourceManager.GetString("DetailMoview_BuyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Editor_ReturnType_Done {
            get {
                return ResourceManager.GetString("Editor_ReturnType_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Editor_ReturnType_Go {
            get {
                return ResourceManager.GetString("Editor_ReturnType_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Editor_ReturnType_Next {
            get {
                return ResourceManager.GetString("Editor_ReturnType_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Editor_ReturnType_Search {
            get {
                return ResourceManager.GetString("Editor_ReturnType_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Editor_ReturnType_Send {
            get {
                return ResourceManager.GetString("Editor_ReturnType_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you internet connection.
        /// </summary>
        public static string ErrorInternetConnection {
            get {
                return ResourceManager.GetString("ErrorInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request cannot be process at this time. Please, try again later..
        /// </summary>
        public static string ErrorNoConnection {
            get {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint could not be read correctly.
        /// </summary>
        public static string Fingerprint_Authenticate_Error {
            get {
                return ResourceManager.GetString("Fingerprint_Authenticate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to authenticate to be able to continue.
        /// </summary>
        public static string Fingerprint_Authenticate_To_Continue {
            get {
                return ResourceManager.GetString("Fingerprint_Authenticate_To_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2019 Cine, Inc. All Rights Reserved.
        /// </summary>
        public static string Login_Footer {
            get {
                return ResourceManager.GetString("Login_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_Forgot_Your_Password {
            get {
                return ResourceManager.GetString("Login_Forgot_Your_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Login_No_Registered {
            get {
                return ResourceManager.GetString("Login_No_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Login_User {
            get {
                return ResourceManager.GetString("Login_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Tickets.
        /// </summary>
        public static string Menu_Drawer_BuyTicket {
            get {
                return ResourceManager.GetString("Menu_Drawer_BuyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge discount.
        /// </summary>
        public static string Menu_Drawer_Collect {
            get {
                return ResourceManager.GetString("Menu_Drawer_Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Drawer_Logout {
            get {
                return ResourceManager.GetString("Menu_Drawer_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Menu_Drawer_Principal {
            get {
                return ResourceManager.GetString("Menu_Drawer_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivia.
        /// </summary>
        public static string Menu_Drawer_Trivia {
            get {
                return ResourceManager.GetString("Menu_Drawer_Trivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password.
        /// </summary>
        public static string System_Current_Password {
            get {
                return ResourceManager.GetString("System_Current_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy.
        /// </summary>
        public static string System_Date_Format_Default {
            get {
                return ResourceManager.GetString("System_Date_Format_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy HH:mm:ss.
        /// </summary>
        public static string System_DateTime_Format_Default {
            get {
                return ResourceManager.GetString("System_DateTime_Format_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string System_From {
            get {
                return ResourceManager.GetString("System_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string System_New_Password {
            get {
                return ResourceManager.GetString("System_New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in process.
        /// </summary>
        public static string System_Process_Error {
            get {
                return ResourceManager.GetString("System_Process_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been canceled.
        /// </summary>
        public static string System_Request_Cancel {
            get {
                return ResourceManager.GetString("System_Request_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request has been successfully processed.
        /// </summary>
        public static string System_Request_Success {
            get {
                return ResourceManager.GetString("System_Request_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string System_To {
            get {
                return ResourceManager.GetString("System_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the application where you can buy tickets to the cinema.
        /// </summary>
        public static string Welcome_Summary {
            get {
                return ResourceManager.GetString("Welcome_Summary", resourceCulture);
            }
        }
    }
}
